# Generated by Django 6.1 on 2026-08-20 18:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('est_loyer', models.BooleanField(default=False, help_text="Coché uniquement pour le type 'Loyer' : réparti entre TOUS les résidents (présents ou non).", verbose_name="C'est le loyer")),
                ('est_wifi', models.BooleanField(default=False, help_text="Coché uniquement pour le type 'Internet/Wifi' : les contributions externes en sont déduites avant répartition.", verbose_name="C'est l'abonnement wifi")),
            ],
            options={
                'verbose_name': 'Type de charge',
                'verbose_name_plural': 'Types de charge',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ExternalContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Contributeur externe (wifi)',
                'verbose_name_plural': 'Contributeurs externes (wifi)',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('cloturee', models.BooleanField(default=False, help_text="Une période clôturée n'est plus modifiable dans l'interface.", verbose_name='Clôturée')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.chargetype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.period')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['charge_type__nom'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, help_text='Décochez pour retirer un résident sans supprimer son historique.', verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résident',
                'verbose_name_plural': 'Résidents',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True, verbose_name='Présent dans la maison')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.period')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.resident')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('resident', 'period')},
            },
        ),
        migrations.CreateModel(
            name='WifiContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.externalcontributor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_contributions', to='core.period')),
            ],
            options={
                'verbose_name': 'Contribution wifi (externe)',
                'verbose_name_plural': 'Contributions wifi (externes)',
                'unique_together': {('period', 'contributor')},
            },
        ),
    ]
