# Generated by Django 6.1 on 2026-08-20 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé (FCFA)')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date du paiement')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.period')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.resident')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'unique_together': {('period', 'resident')},
            },
        ),
    ]
