# Generated by Django 6.1 on 2026-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcontributor',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Téléphone'),
        ),
    ]
